### ISSUE TITLE
出现了问题，发送色图时爆红

### ISSUE THREAD

**Issue by FXDYJ** [Nekoer/mirai-plugins-pixiv#10]
发送色图直接报红，爆红代码如下:
2022-04-12 04:30:19 W/stderr: java.io.IOException: Unexpected response code for CONNECT: 404
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2022-04-12 04:30:19 W/stderr: at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.utils.RequestUtil$Companion.httpObject(RequestUtil.kt:92)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.utils.RequestUtil$Companion.requestObject(RequestUtil.kt:35)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.rank.TotalProcessing.dealWith(TotalProcessing.kt:22)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.sexy.SexyCenter.pixiv(SexyCenter.kt:127)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.sexy.SexyCenter.init(SexyCenter.kt:46)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.Pixiv$onEnable$1$10.invokeSuspend(Pixiv.kt:67)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
2022-04-12 04:30:19 W/stderr: at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
2022-04-12 04:30:19 W/stderr: at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
2022-04-12 04:30:19 W/stderr: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-04-12 04:30:19 W/stderr: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-04-12 04:30:19 W/Pixiv: java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONArray.size()" because "illusts" is null
java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONArray.size()" because "illusts" is null
at com.hcyacg.sexy.SexyCenter.pixiv(SexyCenter.kt:130)
at com.hcyacg.sexy.SexyCenter.init(SexyCenter.kt:46)
at com.hcyacg.Pixiv$onEnable$1$10.invokeSuspend(Pixiv.kt:67)
at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2022-04-12 04:30:20 V/Bot.2819569319: Group(951358735) <- 发送图片失败

**Comment by Nekoer** [comment]
请注意服务器是否是国外服务器，若不是请开启代理并在配置文件中proxy里配置

**Comment by FXDYJ** [comment]
请问怎么检查服务器？

**Comment by Nekoer** [comment]
你是国内服务器，就需要开代理。如果是港澳台或者国外服务器，就不需要

**Comment by FXDYJ** [comment]
怎么开代理？

**Comment by Nekoer** [comment]
```
  proxy:  # http请求代理 下面是clash的例子
    host: 127.0.0.1
    port: 7890
```
[Clash下载地址](https://github.com/Fndroid/clash_for_windows_pkg/releases)

**Comment by FXDYJ** [comment]
现在又有了全新的问题

**Comment by FXDYJ** [comment]
2022-05-01 15:43:53 W/Pixiv: java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:320)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:347)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:800)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.hcyacg.utils.RequestUtil$Companion.httpArray(RequestUtil.kt:112)
        at com.hcyacg.utils.RequestUtil$Companion.requestArray(RequestUtil.kt:63)
        at com.hcyacg.sexy.SexyCenter.konachan(SexyCenter.kt:93)
        at com.hcyacg.sexy.SexyCenter.init(SexyCenter.kt:42)
        at com.hcyacg.Pixiv$onEnable$1$10.invokeSuspend(Pixiv.kt:67)
        at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
        at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by FXDYJ** [comment]
上面的问题解决了

**Comment by FXDYJ** [comment]
又来一个问题

**Comment by FXDYJ** [comment]
2022-05-01 16:15:01 V/Bot.2819569319: Group(951358735) <- [mirai:quote:[889],[1925773990]][mirai:image:{80939D0D-7574-328B-ACC4-4AA5083B389E}.jpg]来源:YANDE(960224)

**Comment by FXDYJ** [comment]
控制台显示发出去了，但是没有
