### ISSUE TITLE
大佬您好，请问一下我装载插件后启动mirai报错

### ISSUE THREAD

**Issue by TaylorEevee** [Nekoer/mirai-plugins-pixiv#11]
这个是启动时的完整日志
  17:36:48 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  17:36:48 [INFO] https://github.com/iTXTech/mirai-console-loader
  17:36:48 [INFO] This program is licensed under GNU AGPL v3
  17:36:49 [INFO] Verifying "net.mamoe:mirai-console" v2.9.0-M1
  17:36:49 [WARN] Package "net.mamoe:mirai-console" has newer version "2.11.0-M2.2"
  17:36:49 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.9.0-M1
  17:36:50 [WARN] Package "net.mamoe:mirai-console-terminal" has newer version "2.11.0-M2.2"
  17:36:50 [INFO] Verifying "net.mamoe:mirai-core-all" v2.9.0-M1
  17:36:50 [WARN] Package "net.mamoe:mirai-core-all" has newer version "2.11.0-M2.2"
  17:36:50 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  17:36:50 [WARN] Run ./mcl -u to update packages.
  17:36:50 [INFO] Fetching Mirai Console Loader Announcement...
  17:36:50 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
如果无法获取Mirai-Repo信息, 例如启动时出现JSON解析错误
请升级到MCL 2.0 Beta并将 config.json 中的 Mirai-Repo 更改为 https://repo.itxtech.org

2022-04-22 17:36:50 I/main: Starting mirai-console...
2022-04-22 17:36:50 I/main: Backend: version 2.9.0-M1, built on 2021-11-21 07:59:25.
2022-04-22 17:36:50 I/main: Frontend Terminal: version 2.9.0-M1, provided by Mamoe Technologies
2022-04-22 17:36:50 I/main: Welcome to visit https://mirai.mamoe.net/
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin Mesagisto v1.0.0
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin p_0-Author-HRS-LSys-Loaded v0.2.9
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin pixiv插画 v1.6.5
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin plugin_5 Author - HRS LSys GetSong Loaded v0.1
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-04-22 17:36:51 I/plugin: Successfully loaded plugin plugin_4 Author - HRS LSys GetPic Loaded v0.1
2022-04-22 17:36:51 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2022-04-22 17:36:51 I/Mesagisto: Trying to connect to nats server: nats://itsusinn.site:4222
2022-04-22 17:36:51 I/Mesagisto: Connect nats successfully
2022-04-22 17:36:51 I/Mesagisto: 信使插件已启用
2022-04-22 17:36:51 I/p_0-Author-HRS-LSys-Loaded: HRS's LSys Plugin loaded! @作者:qq-3474006766
2022-04-22 17:36:51 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-04-22 17:36:51 E/pixiv插画: java.lang.NoSuchMethodError: 'kotlin.reflect.KType kotlin.jvm.internal.Reflection.mutableCollectionType(kotlin.reflect.KType)'
java.lang.NoSuchMethodError: 'kotlin.reflect.KType kotlin.jvm.internal.Reflection.mutableCollectionType(kotlin.reflect.KType)'
        at com.hcyacg.initial.Setting.<clinit>(Setting.kt:23)
        at com.hcyacg.Pixiv.onEnable(Pixiv.kt:47)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:122)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:214)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)

2022-04-22 17:36:51 I/plugin_5 Author - HRS LSys GetSong Loaded: 
2022-04-22 17:36:51 I/plugin_4 Author - HRS LSys GetPic Loaded: 
2022-04-22 17:36:51 I/main: 7 plugin(s) enabled.
2022-04-22 17:36:51 I/main: Auto-login 2946319131
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-04-22 17:36:52 I/Bot.2946319131: Loaded account secrets from local cache.
2022-04-22 17:36:53 I/Bot.2946319131: Saved account secrets to local cache for fast login.
2022-04-22 17:36:53 I/Bot.2946319131: Login successful.
2022-04-22 17:36:53 V/Bot.2946319131: Event: BotOnlineEvent(bot=Bot(2946319131))
2022-04-22 17:36:53 I/Bot.2946319131: Bot login successful.
2022-04-22 17:36:53 I/main: mirai-console started successfully.
2022-04-22 17:40:54 V/Bot.2946319131: Event: OtherClientOfflineEvent(client=OtherClient(bot=2946319131,deviceName=mirai,platform=IOS))
2022-04-22 17:41:00 V/Bot.2946319131: Event: OtherClientOnlineEvent(client=OtherClient(bot=2946319131,deviceName=mirai,platform=IOS), kind=MOBILE_HD)

**Comment by Nekoer** [comment]
你的mirai版本2.9.0-M1太低，最新版插件用的是[2.11.0-M2.2](https://github.com/mamoe/mirai/releases/tag/v2.11.0-M2.2)

**Comment by TaylorEevee** [comment]
好的，感谢dalao
