### ISSUE TITLE
发送色图时报错

### ISSUE THREAD

**Issue by FXDYJ** [Nekoer/mirai-plugins-pixiv#13]
报错内容如下：2022-05-03 16:58:42 W/stderr: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1709)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2022-05-03 16:58:42 W/stderr:   at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.utils.RequestUtil$Companion.httpObject(RequestUtil.kt:92)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.utils.RequestUtil$Companion.requestObject(RequestUtil.kt:35)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.rank.TotalProcessing.dealWith(TotalProcessing.kt:22)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.sexy.SexyCenter.pixiv(SexyCenter.kt:127)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.sexy.SexyCenter.init(SexyCenter.kt:46)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.Pixiv$onEnable$1$10.invokeSuspend(Pixiv.kt:67)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
2022-05-03 16:58:42 W/stderr:   at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
2022-05-03 16:58:42 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
2022-05-03 16:58:42 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-05-03 16:58:42 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-05-03 16:58:42 W/stderr: Caused by: java.io.EOFException: SSL peer shut down incorrectly
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
2022-05-03 16:58:42 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
2022-05-03 16:58:42 W/stderr:   ... 56 more
2022-05-03 16:58:42 W/Pixiv: java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONArray.size()" because "illusts" is null
java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONArray.size()" because "illusts" is null
        at com.hcyacg.sexy.SexyCenter.pixiv(SexyCenter.kt:130)
        at com.hcyacg.sexy.SexyCenter.init(SexyCenter.kt:46)
        at com.hcyacg.Pixiv$onEnable$1$10.invokeSuspend(Pixiv.kt:67)
        at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
        at com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2022-05-03 16:58:42 V/Bot.2819569319: Group(951358735) <- 发送图片失败

**Comment by Nekoer** [comment]
你确定你的服务器能访问`api.acgmx.com`吗

**Comment by Nekoer** [comment]
我现在感觉是你网络有问题无法访问到接口

**Comment by FXDYJ** [comment]
能，用浏览器打开显示{"code":401,"error":"没有携带Token信息","msg":"服务器错误"}

**Comment by Nekoer** [comment]
是在你的服务器里打开的吗

**Comment by Nekoer** [comment]
方便的话加群私聊我服务器账户密码，我进去看看是什么原因

**Comment by FXDYJ** [comment]
问题好了

**Comment by FXDYJ** [comment]
但是有了个全新的问题

**Comment by FXDYJ** [comment]
控制台显示发出去了，实际上并没有

**Comment by FXDYJ** [comment]
群号是多少

**Comment by FXDYJ** [comment]
不用了，找到你的QQ了

**Comment by Nekoer** [comment]
> 控制台显示发出去了，实际上并没有

这个是你机器人被腾讯风控了，挂几天自动恢复，我也无法解决

**Comment by FXDYJ** [comment]
谢谢
