### ISSUE TITLE
使用搜番功能报错

### ISSUE THREAD

**Issue by Tamamoimoto** [Nekoer/mirai-plugins-pixiv#46]
### 问题描述

搜番用了就报错
系统：armbian     Linux onecloud 5.18.0-rc3-meson #trunk SMP Thu Jun 30 13:19:36 UTC 2022 armv7l GNU/Linux
mirai-2.12
MCL-2.1.0

### 复现

无法使用搜番功能
发送ptsf-
![@13CAN04(0Z (A0ATHDLIA6](https://user-images.githubusercontent.com/37890702/178448030-ff419c9e-3ff4-47a8-a834-6f1b97379703.png)后，BOT无反应后台报错。

### pixiv 版本

1.7.4

### 系统日志

```text
2022-07-12 16:32:21 E/pixiv插画: Exception in coroutine Plugin com.hcyacg.pixiv of pixiv插画
java.lang.NumberFormatException: For input string: "null"
        at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.base/java.lang.Long.parseLong(Unknown Source)
        at java.base/java.lang.Long.parseLong(Unknown Source)
        at pixiv-1.7.4-future-2.mirai.jar//com.hcyacg.search.Trace.searchInfoByPic(Trace.kt:108)
        at pixiv-1.7.4-future-2.mirai.jar//com.hcyacg.Pixiv$onEnable$1$8.invokeSuspend(Pixiv.kt:85)
        at pixiv-1.7.4-future-2.mirai.jar//com.hcyacg.Pixiv$onEnable$1$8.invoke(Pixiv.kt)
        at pixiv-1.7.4-future-2.mirai.jar//com.hcyacg.Pixiv$onEnable$1$8.invoke(Pixiv.kt)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$quoteReply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$quoteReply$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.event.MessageSubscribersBuilder$quoteReply$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
        at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:125)
        at net.mamoe.mirai.internal.event.EventListeners.access$process(EventListeners.kt:33)
        at net.mamoe.mirai.internal.event.EventListeners$callListeners$2$1.invokeSuspend(EventListeners.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Nekoer** [comment]
fix: [`c2ef21e`](https://github.com/Nekoer/mirai-plugins-pixiv/commit/c2ef21eb78fc2a9f673f92c5d8aaa453b3d86d0e)
