### ISSUE TITLE
似乎跟onebot-mirai有冲突

### ISSUE THREAD

**Issue by SnowMoonSS** [Nekoer/mirai-plugins-pixiv#48]
### 问题描述

使用setu指令的时候图片发送失败

### 复现

使用setu命令

### pixiv 版本

1.6.8

### 系统日志

```text
2022-07-16 10:41:01 V/Bot.0123456789: [abcd(123456789)] 猫猫bot(123456789) -> 涩图
2022-07-16 10:41:01 W/pixiv插画: Linked class okhttp3.Headers$Builder in onebot-mirai-0.3.4-all-disYamlkt.jar but plugin not depend on it.
2022-07-16 10:41:01 W/pixiv插画: Class loading logic may change in feature.
2022-07-16 10:41:02 W/SexyCenter: java.lang.NullPointerException
java.lang.NullPointerException
	at pixiv-1.6.8.jar//com.hcyacg.sexy.SexyCenter.pixiv(SexyCenter.kt:231)
	at pixiv-1.6.8.jar//com.hcyacg.sexy.SexyCenter.init(SexyCenter.kt:83)
	at pixiv-1.6.8.jar//com.hcyacg.Pixiv$onEnable$1$10.invokeSuspend(Pixiv.kt:82)
	at pixiv-1.6.8.jar//com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
	at pixiv-1.6.8.jar//com.hcyacg.Pixiv$onEnable$1$10.invoke(Pixiv.kt)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$reply$3.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:125)
	at net.mamoe.mirai.internal.event.EventListeners.access$process(EventListeners.kt:33)
	at net.mamoe.mirai.internal.event.EventListeners$callListeners$2$1.invokeSuspend(EventListeners.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-07-16 10:41:02 V/Bot.0123456789: Group(123456789) <- 发送图片失败
```
```


### 网络日志

_No response_

### 补充信息

_No response_

**Comment by Nekoer** [comment]
请下载最新版本

**Comment by SnowMoonSS** [comment]
我超，怎么mcl库里的不是最新版……
