### ISSUE TITLE
AutoUpdate

### ISSUE THREAD

**Issue by LookStars** [Nekoer/mirai-plugins-pixiv#66]
### 问题描述

运行之后就更新1.7.5更新总是会失败，第二次启动会因为插件里面有个1.7.5的不完整体出现致命错误

### 复现

删除1.7.5版本插件
运行./mcl

### pixiv 版本

1.7.4

### 系统日志

```text
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 0 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 0 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 0 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 0 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 0 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 1 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 1 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 1 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 1 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 1 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 1 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 2 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 2 %
2022-12-06 00:53:52 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 2 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 2 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 2 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 3 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 3 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 3 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 3 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 3 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 3 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 4 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 4 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 4 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 4 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 4 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 5 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 5 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 5 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 5 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 5 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 5 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 6 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 6 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 6 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 6 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 6 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 7 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 7 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 7 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 7 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 7 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 8 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 8 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 8 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 8 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 8 %
2022-12-06 00:53:53 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 8 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 9 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 9 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 9 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 9 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 9 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 10 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 10 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 10 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 10 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 10 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 10 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 11 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 11 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 11 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 11 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 11 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 12 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 12 %
2022-12-06 00:53:53 I/AutoUpdate: pixiv-1.7.5.mirai2.jar 已下载 12 %
2022-12-06 00:53:53 W/AutoUpdate: pixiv-1.7.5.mirai2.jar 更新失败

第二次运行时:
./mcl -u
  00:56:12 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  00:56:12 [INFO] Runtime: Java HotSpot(TM) 64-Bit Server VM 17.0.1 (arch: 64)
  00:56:12 [INFO] https://github.com/iTXTech/mirai-console-loader
  00:56:12 [INFO] This program is licensed under GNU AGPL v3
  00:56:14 [INFO] Mirai Plugins Pixiv Announcement:
从1.6.5开始请使用Mirai 2.11.0-M2.2
  00:56:14 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  00:56:14 [INFO] Verifying "net.mamoe:mirai-console" v2.12.3
  00:56:14 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.12.3
  00:56:14 [INFO] Verifying "net.mamoe:mirai-core-all" v2.12.3
  00:56:15 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  00:56:15 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
  00:56:15 [INFO] Verifying "com.hcyacg:pixiv" v1.7.4
2022-12-06 00:56:16 I/main: Starting mirai-console...
2022-12-06 00:56:16 I/main: Backend: version 2.12.3, built on 2022-09-11 21:02:46.
2022-12-06 00:56:16 I/main: Frontend Terminal: version 2.12.3, provided by Mamoe Technologies
2022-12-06 00:56:16 I/main: Welcome to visit https://mirai.mamoe.net/
2022-12-06 00:56:17 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-12-06 00:56:17 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-12-06 00:56:17 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-12-06 00:56:17 E/main: Failed to init MiraiConsole.
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init0(JvmPluginClassLoader.kt:225)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt:221)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN$Companion.newLoader(JvmPluginClassLoader.kt:325)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:182)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:66)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:192)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:138)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:148)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:178)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
```

**Comment by LookStars** [comment]
.好像mirai包里下载的就是1.7.4 新版fix好像已经修复了

**Comment by Nekoer** [comment]
请去下载预发布测试版
