### ISSUE TITLE
搜番功能不能正常使用

### ISSUE THREAD

**Issue by 1233Ao** [Nekoer/mirai-plugins-pixiv#67]
### 问题描述

提示E/Trace: 您未使用FFmpeg版本,将缺少视频转Gif的功能，不知道这个怎么解决，信息发布出去

### 复现

电脑装了FFmpeg，但是下载releases里的1.7.5版本使用搜番功能提示您未使用FFmpeg版本,将缺少视频转Gif的功能，信息无法发送

### pixiv 版本

不知道

### 系统日志

```text
2022-12-17 15:24:03 V/Bot.2016401389: [佩奇养老院(111111111)] 1233(11111111) -> ptsf-[mirai:image:{177EA2C9-5C6D-9A1B-01A3-FC274D4DD968}.png, width=629, height=350, size=209627, type=PNG, isEmoji=false]
2022-12-17 15:24:03 I/stdout: RobotConfig.enableRobot = true
2022-12-17 15:24:12 V/Bot.2016401389: Group(724983049) <- [mirai:at:3031917948] \n[mirai:image:{EAA04A23-99FE-824F-6638-5635657042F7}.jpg, width=460, height=646, size=82057, type=JPG, isEmoji=false]\n番名：魔女の旅々\n别名：Majo no Tabitabi - 08 (BD 1280x720 x264 AAC).mp4\n集数：8\n出现在：00:07:54 - 00:07:54\n相似度：88.84%
2022-12-17 15:24:39 E/Trace: 您未使用FFmpeg版本,将缺少视频转Gif的功能
2022-12-17 15:24:39 E/pixiv插画: Exception in coroutine Plugin com.hcyacg.pixiv of pixiv插画
java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@430dd3e8, considering use gif/png/bmp/jpg format. image header:
        at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda-16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 补充信息

[2022-12-17.log](https://github.com/Nekoer/mirai-plugins-pixiv/files/10251174/2022-12-17.log)

**Comment by Nekoer** [comment]
使用FFmpeg版本需要你下载插件源码修改一下依赖，编译后使用。
并非BUG

**Comment by 1233Ao** [comment]
有编译好的吗
