### ISSUE TITLE
似乎tag标签超过两个字就会报错

### ISSUE THREAD

**Issue by jinxx52** [Nekoer/mirai-plugins-pixiv#7]
`2022-04-07 16:54:09 V/Bot.1115706211: [锦创建的群(543943710)] 身骑白马(1115706226) -> tag-格蕾修-1
2022-04-07 16:54:09 W/stderr: java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
2022-04-07 16:54:09 W/stderr:   at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
2022-04-07 16:54:09 W/stderr:   at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
2022-04-07 16:54:09 W/stderr:   at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
2022-04-07 16:54:09 W/stderr:   at java.base/java.util.Objects.checkIndex(Objects.java:359)
2022-04-07 16:54:09 W/stderr:   at java.base/java.util.ArrayList.get(ArrayList.java:427)
2022-04-07 16:54:09 W/stderr:   at pixiv-1.6.4.mirai.jar//com.alibaba.fastjson.JSONArray.get(JSONArray.java:240)
2022-04-07 16:54:09 W/stderr:   at pixiv-1.6.4.mirai.jar//com.hcyacg.rank.Tag.init(Tag.kt:61)
2022-04-07 16:54:09 W/stderr:   at pixiv-1.6.4.mirai.jar//com.hcyacg.Pixiv$onEnable$1$12.invokeSuspend(Pixiv.kt:71)
2022-04-07 16:54:09 W/stderr:   at pixiv-1.6.4.mirai.jar//com.hcyacg.Pixiv$onEnable$1$12.invoke(Pixiv.kt)
2022-04-07 16:54:09 W/stderr:   at pixiv-1.6.4.mirai.jar//com.hcyacg.Pixiv$onEnable$1$12.invoke(Pixiv.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.MessageSubscribersBuilder$quoteReply$3.invokeSuspend(MessageSubscribersBuilder.kt:510)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.MessageSubscribersBuilder$quoteReply$3.invoke(MessageSubscribersBuilder.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.MessageSubscribersBuilder$quoteReply$3.invoke(MessageSubscribersBuilder.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
2022-04-07 16:54:09 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
2022-04-07 16:54:09 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-04-07 16:54:09 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-04-07 16:54:26 V/Bot.1115706211: [锦创建的群(543943710)] 身骑白马(1115706226) -> tag-格蕾-1
2022-04-07 16:54:27 V/Bot.1115706211: Group(543943710) <- [mirai:at:1115706226] \n======标签排行榜(格蕾)======\n1. 格蕾修！！ - 箩莉即正义 - 96899548\n2. Griseo "Star" - Reina - 96878028\n3. Griseo - MilliAni - 96841427\n4. 「繁星」格蕾修 - 鱼树 - 96835544\n5. 繁星 - 捏噗噗捏 - 96824064\n6. 全家福 - FAT 24K - 95876769\n7. 20211011 - 心之颜白鸟 - 95185003\n8. The Beauty of Death（作品合集 11） - 暗蛟 - 94828232\n9. ミツバ·グレイヴァレ? （ 三叶?格蕾华莱） - 暗蛟 - 94739530\n10. ミツバ·グレイヴァレ? （三叶?格蕾华莱）  AO底稿（大概吧） - 暗蛟 - 94020996\n
`
两个字输出的是正常的

**Comment by Nekoer** [comment]
Fixed and released in the next release
