### ISSUE TITLE
hcyacg中的i.acgmx.com的ssl证书已过期

### ISSUE THREAD

**Issue by MoeShimaKaze** [Nekoer/mirai-plugins-pixiv#79]
### 问题描述

昨天晚上到现在发现HCYACG的功能不可用，查看后发现为SSL证书过期，还请麻烦作者更新一下（

### 复现

调用任意使用Hcyacg API功能，即可复现

### pixiv 版本

1.7.8

### 系统日志

```text
2024-12-09 11:13:38 W/Companion: https://i.acgmx.com/img-original/img/2023/01/07/12/28/43/104309262_p0.jpg获取失败,请检查网络
2024-12-09 11:13:38 W/stderr: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1351)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:206)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.ConnectPlan.connectTls(ConnectPlan.kt:323)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:188)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.SequentialExchangeFinder.find(SequentialExchangeFinder.kt:35)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar//com.hcyacg.utils.ImageUtil$Companion.getImage(ImageUtil.kt:61)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar//com.hcyacg.sexy.LoliconCenter.load(LoliconCenter.kt:141)
2024-12-09 11:13:38 W/stderr: 	at pixiv-1.7.8.mirai2.jar//com.hcyacg.sexy.LoliconCenter$load$1.invokeSuspend(LoliconCenter.kt)
2024-12-09 11:13:38 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-12-09 11:13:38 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-12-09 11:13:38 W/stderr: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
2024-12-09 11:13:38 W/stderr: 	... 37 more
2024-12-09 11:13:38 W/stderr: Caused by: java.security.cert.CertPathValidatorException: validity check failed
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
2024-12-09 11:13:38 W/stderr: 	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
2024-12-09 11:13:38 W/stderr: 	... 42 more
2024-12-09 11:13:38 W/stderr: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Mon Dec 09 07:12:47 CST 2024
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:621)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
2024-12-09 11:13:38 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
2024-12-09 11:13:38 W/stderr: 	... 47 more
2024-12-09 11:13:38 W/stderr: java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@3e013adc, considering use gif/png/bmp/jpg format. image header: 
2024-12-09 11:13:38 W/stderr: 	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
2024-12-09 11:13:38 W/stderr: 	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda$16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2024-12-09 11:13:38 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-12-09 11:13:38 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-12-09 11:13:38 V/Bot.2041258171: Group(535189356) <- [mirai:quote:[mirai:source:ids=[1222997], internalIds=[663706772], from group 3564661687 to 535189356 at 1733714014], content=loli 眼镜&萝莉]服务错误
2024-12-09 11:13:44 V/Bot.2041258171: [ForeActos-似水流年(535189356)] Anki_Kaze(717305836) -> ?
2024-12-09 11:13:45 V/Bot.2041258171: [ForeActos-似水流年(535189356)] Anki_Kaze(717305836) -> 不是
2024-12-09 11:13:59 V/Bot.2041258171: [ForeActos-似水流年(535189356)] Earthmoon(3564661687) -> [不支持的消息#309858393]
2024-12-09 11:14:09 V/Bot.2041258171: [ForeActos-似水流年(535189356)] Anki_Kaze(717305836) -> psid-62702847
2024-12-09 11:14:10 V/Bot.2041258171: Group(535189356) <- [mirai:at:717305836] 正在获取中,请稍后
2024-12-09 11:14:11 W/Companion: https://i.acgmx.com/img-original/img/2017/05/03/00/00/04/62702847_p0.png获取失败,请检查网络
2024-12-09 11:14:11 W/stderr: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1351)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:206)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.ConnectPlan.connectTls(ConnectPlan.kt:323)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:188)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.SequentialExchangeFinder.find(SequentialExchangeFinder.kt:35)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar[private]//okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar//com.hcyacg.utils.ImageUtil$Companion.getImage(ImageUtil.kt:61)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar//com.hcyacg.details.PicDetails.load(PicDetails.kt:224)
2024-12-09 11:14:11 W/stderr: 	at pixiv-1.7.8.mirai2.jar//com.hcyacg.details.PicDetails$load$1.invokeSuspend(PicDetails.kt)
2024-12-09 11:14:11 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-12-09 11:14:11 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-12-09 11:14:11 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-12-09 11:14:11 W/stderr: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
2024-12-09 11:14:11 W/stderr: 	... 37 more
2024-12-09 11:14:11 W/stderr: Caused by: java.security.cert.CertPathValidatorException: validity check failed
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
2024-12-09 11:14:11 W/stderr: 	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
2024-12-09 11:14:11 W/stderr: 	... 42 more
2024-12-09 11:14:11 W/stderr: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Mon Dec 09 07:12:47 CST 2024
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:621)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
2024-12-09 11:14:11 W/stderr: 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
2024-12-09 11:14:11 W/stderr: 	... 47 more
2024-12-09 11:14:11 E/pixiv插画: Exception in coroutine Plugin com.hcyacg.pixiv of pixiv插画
java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@51e14974, considering use gif/png/bmp/jpg format. image header: 
	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda$16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Nekoer** [comment]
已恢复
